---
title: "Documentation"
author: Minghan Yang
date: today
format:
  html:
    theme: flatly
    code-fold: false
    toc: true
    number-sections: true
execute:
  kernel: julia
  options:
    threads: 8  # Set the number of threads here
bibliography: references.bib
---
including the hazard-response model description, and some of the key codes and plots to describe the processes.
Yes, I think you can start with a description of the hazard response model (directly, without going into the general formulation of ODEs), followed by a discussion on how to fix the initial conditions.
After that, you can follow the code and add any text of formulas before the code, simply to explain what are you calculating. For instance, presenting the general formula of the likelihood function and explaining that you need a solver. Then, followed by a description of the priors that you will use, and a reference to Turing.jl. Then, a little description of the predictive hazard, and a brief discussion of the summaries you will present.
It does not need to be very extensive, just simply formulas that explain what you are running in each chunk of code.

# Survival Analysis Overview
Survival analysis is often used in areas such as biology, medicine, and engineering. For cancer studies, one typical topic is the survival of cancer patients after a diagnosis of cancer.

The data used in survival analysis is often sample of \textbf{times to event} from a population ($t_1, t_2, \ldots, t_n$). in our project, we use the breast cancer patient data from hospitals in Rotterdam. 

* Survival Time: The duration of time from a starting point (for example, diagnosis of a disease) to the occurrence of an event (e.g. death). 

* Vital status (censoring indicators): $\delta_1, \delta_2, \ldots, \delta_n$. 
    
    $\delta_i=1$: death, 
    
    $\delta_i=0$: alive / right-censored.

In many studies, some subjects may not experience the event before the study ends, leading to censored data. Survival analysis methods can appropriately handle these censored observations. It helps estimate survival rates at different time points, which is vital for predicting and understanding the progression of diseases, patient outcomes, and the effectiveness of treatments.

## Censoring
Censoring occurs when the exact time of the event is not known for some subjects. This happens for various reasons, such as the study ending before the event occurs, the subject withdrawing from the study, or loss to follow-up. For example, if a study ends before a patient dies or if a patient leaves the study early, their data is \emph{censored}. If death, failure of a machine or relapse of a disease happens, then the data is an \emph{event}.

1. **Right Censoring**

Right censoring occurs when the event of interest has not happened by the end of the study period for some subjects. We only know that the event time exceeds a certain value.    

Right-censoring is a common feature in survival data and must be appropriately handled to avoid bias in the analysis. Survival analysis techniques, like the Kaplan-Meier estimator and Cox proportional hazards model, are specifically designed to deal with right-censored data, allowing researchers to make valid inferences about the time-to-event process even when not all events are observed.

2. **Left Censoring**

Left censoring happens when the event of interest has already occurred before the subject is observed or enters the study. We only know that the event time is less than a certain value.

If a subject is left-censored at time $t$, it means the event time $T$ is less than $t$.

3. **Interval Censoring**

Interval censoring occurs when the event time is known to lie within a specific interval but the exact time is unknown.

4. **Administrative Censoring**

Administrative censoring refers to the situation where all subjects are censored at a predefined time point due to the end of the study.

5. **Random Censoring**

Random censoring occurs when the censoring times are random and independent of the event times. For example, subjects dropping out of a study at random times due to various reasons such as relocation or withdrawal.

## Functions
1. **Lifetime distribution function**

\begin{equation}
    F(t) = \mathbb{P}(T<t), x\geq 0.
\end{equation}
This function describes the probability of failing up age of t or of having a life span of at most t. $F(t)$ is a monotone and increasing function. $0 \leq F(t) \leq 1$. The derivative of $F(t)$ is the corresponding PDF $f(t)$.

2. **Survival function**

The survival function is another representative of lifetime distribution. It is defined as
\begin{equation}
    S(t)= \mathbb{P}(T>t) = 1-F(t)=\mathbb{P}(T>t)
\end{equation}
The survival function is also known as the reliability function, indicating the probability of surviving a time of $t$. It is the probability of exceeding time $t$. The study of survival function is crucial in survival analysis.

**Properties:**

* The survival function $S(t)$ is monotone and decreasing over $[0, \infty)$. Furthermore, $S(t)$ satisfies $S(0) = 1$, $S(\infty) = 0$.
* The survival function is related to $F(t)$: $S(t)=1 - F(t)$.
* The survival function appropriately handles right-censored data. Censored observations contribute information up until the censoring time but not beyond it. This allows the survival function to provide unbiased estimates even when not all subjects have experienced the event by the end of the study.


3. **Hazard function**

Hazard function is defined to be $$h(t) = \lim_{ dt \to 0} \frac{\mathbb{P}[t \leq T \leq t + dt \mid T \geq t]}{ dt}. $$
This describes the instantaneous rate at which events occur, given no previous event. It is the probability that an event occurs in a very small time interval, given survival up to the start of the interval.

The hazard function is the ratio of the probability of the event occurring at time $t$ to the probability of surviving up to time $t$.
\begin{equation}
    h(t)=\frac{f(t)}{S(t)}
\end{equation}
Proof: 
\begin{align*}
    h(t) &= \lim_{dt \to 0} \frac{\mathbb{P}[t \leq T \leq t + dt | T \geq t]}{dt} \\
    &= \lim_{dt \to 0} \frac{\mathbb{P}[t \leq T \leq t + dt , T \geq t]}{dt \cdot \mathbb{P}(T\geq t)} \\
    &= \lim_{dt \to 0} \frac{\mathbb{P}[t \leq T \leq t + dt]}{dt \cdot \mathbb{P}(T\geq t)} \\
    &= \lim_{dt \to 0} \frac{\mathbb{P}[t \leq T \leq t + dt]}{dt} \cdot \frac{1}{\mathbb{P}(T\geq t)} \\
    &= f(t) \cdot \frac{1}{S(t)}   \quad \blacksquare
\end{align*}
**Properties:**

* $f(0)=h(0)$
* $f(t) \geq h(t), \forall t>0$, because $S(t) \leq 1, \forall t > 0$
* $h(t)$ is \emph{not} a density function because it is not normalised.
* Any function $h(t)$ is a hazard rate function iff:
    i) $h(t) \geq 0, \forall t \geq 0$
    ii) $\int_0^{\infty} h(t) \, dt = \infty$
* The survival function can be expressed in terms of the hazard function:
    \begin{equation}
        S(t) = \exp \left\{ - \int_{0}^{t} h(u) \, du \right\}
    \end{equation}
    Proof: 
    \begin{align*}
        h(t) &= \frac{f(t)}{S(t)} = \frac{F'(t)}{1-F(t)} = - \frac{S'(t)}{S(t)} = - \frac{d}{dt}(\ln{S(t)})\\
        \int_0^t h(u) \,du &= - [\ln{S(u)}]_0^t = -\ln{S(t)} + \ln{S(0)} = -\ln{S(t)} \quad \text{, as $S(0)=1$} \\
        \therefore S(t) &= \exp\left\{- \int_0^t h(u) \, du\right\} \quad \blacksquare
    \end{align*}

4. **Cumulative hazard function**

The function 
\begin{equation}
    H(t) = \int_0^t h(s) \, ds
\end{equation}
is known as the cumulative hazard function.

**Properties:**

* $H(0)=0$
* $\lim_{t \to \infty}$ $H(t) = \infty$
* $H(t)$ is non-decreasing
* $H(t) = - \ln{S(t)} = - \ln{[1-F(t)]}$

5. **Likelihood Function**

When $\delta_i=0$, i.e. alive/right-censored, $L_i=S(t_i\mid \theta)$.

The likelihood function is given by 
\begin{align*}
    L(\theta) &= \prod_{i=1}^n f(t_i \mid \theta)^{\delta_i} S(t_i \mid \theta)^{1-\delta_i} \\
    &= \prod_{i=1}^n [h(t_i \mid \theta) \cdot S(t_i \mid \theta)]^{\delta_i} S(t_i \mid \theta)^{1-\delta_i}, \quad \text{because $h(t)=f(t)/S(t)$}\\
    &= \prod_{i=1}^n h(t_i \mid \theta)^{\delta_i} \cdot \exp \left\{ -H(t_i \mid \theta) \right\}, \quad \text{because $S(t) = \exp \left\{-H(t) \right\}$}
\end{align*}
Therefore, the log-likelihood is 
\begin{equation}
    \ell (\theta) = \sum_{i=1}^n \delta_i \log h(t_i \mid \theta, Y_0) - \sum_{i=1}^n H(t_i \mid \theta, Y_0).
\end{equation}
This allows for calculating the maximum likelihood estimates of the parameters $\theta$ after a hazard function is specified. Also, this is useful in Bayesian framework.

# Hazard-Response Model
ODEs are used to characterise many physical systems, and using the system of ODEs to define the hazard function adds dynamics and interpretability. Here, we use the competitive Lotka-Volterra model to describe the competition between the hazard and response (from therapy, interventions and immune system). This model assumes the competing relationship between the hazard function $f(t)$ and the response $q(t)$, which is related to the immune system and interventions recieved at a population level [@Rubio]. The hazard-response model is defined through the below system of ODEs. 
$$
\begin{cases}
    h'(t) = \lambda h(t) \left( 1-\frac{h(t)}{\kappa}\right) - \alpha q(t) h(t), \quad &h(0)=h_0\\
    q'(t) = \beta q(t) \left( 1-\frac{q(t)}{\kappa}\right) -\alpha q(t) h(t) , \quad &q(0)=q_0\\
    H'(t) = h(t), \quad  &H(0)=0
\end{cases}
$$
where $\lambda > 0$, $\alpha \geq 0$, $\beta > 0$, $\kappa > 0$, $h_0 > 0$, $q_0 > 0$. The competition between hazard and response is modeled through $\alpha q(t) h(t)$, and the growth of the two are given by the logistic growth part $\lambda h(t) \left( 1-\frac{h(t)}{\kappa}\right)$. 

When $\alpha = 0$, there is no competition, and the hazard function will grow and reach a carrying capacity of $\kappa$ as the time tends to infinity. When $\alpha > 0$, both the hazard and the response will receive negative effect from the term $- \alpha q(t) h(t)$.

**Fixing the initial conditions**
To numerically solve the system of ODEs, we need to specify the initial conditions $h_0$ and $q_0$. Based on prior knowledge, 


# Model Formulation and Codes

```{julia}
# Hazard-Response ODE model
function HazResp(dh, h, p, t)
    # Model parameters
    lambda, kappa, alpha, beta = p

    # ODE System
    dh[1] = lambda * h[1] * (1 - h[1] / kappa) - alpha * h[1] * h[2] # hazard
    dh[2] = beta * h[2] * (1 - h[2] / kappa) - alpha * h[1] * h[2] # response
    dh[3] = h[1] # cumulative hazard
    return nothing
end
```


Why we need Jacobian here? For stability. We calculate the Jacobian manually to avoid com-
putational instability caused by numerical approximation of the derivatives.

```{julia}
# Jacobian for Hazard-Response model

function jacHR(J, u, p, t)
    # Parameters
    lambda, kappa, alpha, beta = p
    # state variables
    h = u[1]
    q = u[2]

    # Jacobian
    J[1, 1] = lambda * (1 - 2 * h / kappa) - alpha * q
    J[1, 2] = -alpha * h
    J[1, 3] = 0.0
    J[2, 1] = -alpha * q
    J[2, 2] = beta * (1 - 2 * q / kappa) - alpha * h
    J[2, 3] = 0.0
    J[3, 1] = 1.0
    J[3, 2] = 0.0
    J[3, 3] = 0.0
    nothing
end

```

The log hazard response model:
How is the log scale helping?

```{julia}
# Hazard-Response ODE model
function HazRespL(dlh, lh, p, t)
    # Model parameters
    lambda, kappa, alpha, beta = p

    # ODE System
    dlh[1] = lambda * (1 - exp(lh[1]) / kappa) - alpha * exp(lh[2]) # log hazard
    dlh[2] = beta * (1 - exp(lh[2]) / kappa) - alpha * exp(lh[1]) # log response
    dlh[3] = exp(lh[1]) # cumulative hazard
    return nothing
end

# Jacobian for Hazard-Response model

function jacHRL(J, u, p, t)
    # Parameters
    lambda, kappa, alpha, beta = p
    # state variables
    lh = u[1]
    lq = u[2]

    # Jacobian
    J[1, 1] = -lambda * exp(lh) / kappa
    J[1, 2] = -alpha * exp(lq)
    J[1, 3] = 0.0
    J[2, 1] = -alpha * exp(lh)
    J[2, 2] = -beta * exp(lq) / kappa
    J[2, 3] = 0.0
    J[3, 1] = exp(lh)
    J[3, 2] = 0.0
    J[3, 3] = 0.0
    nothing
end
```

# Bayesian Methods


# Turing


# Predictive Hazard


# Some Results

# Summary
Future work, adding covariates. 